import requests
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
MURF_API_KEY = os.getenv("MURF_API_KEY")

# LLM client
llm_client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

# TTS function
def text_to_speech(text):
    response = requests.post(
        "https://in.api.murf.ai/v1/speech/stream",
        headers={
            "Content-Type": "application/json",
            "api-key": MURF_API_KEY
        },
        json={
            "voice_id": "Nikhil",
            "style": "Conversational",
            "model": "FALCON",
            "text": text
        }
    )
    if response.status_code == 200:
        with open("output.mp3", "wb") as f:
            f.write(response.content)
        print("🔊 Audio saved — output.mp3")
    else:
        print(f"TTS Error: {response.status_code}")

# Conversation
conversation_history = []

print("Voice AI Agent ready! Type 'quit' to exit.")
print("-" * 40)

while True:
    user_input = input("You: ")

    if user_input.lower() == "quit":
        break

    conversation_history.append({
        "role": "user",
        "content": user_input
    })

    try:
        response = llm_client.chat.completions.create(
            model="stepfun/step-3.5-flash:free",
            messages=conversation_history,
            stream=True
        )

        ai_reply = ""
        print("AI: ", end="", flush=True)

        for chunk in response:
            if chunk.choices[0].delta.content:
                word = chunk.choices[0].delta.content
                print(word, end="", flush=True)
                ai_reply += word

        print("\n")

        conversation_history.append({
            "role": "assistant",
            "content": ai_reply
        })

        # send message generated by llm to tts
        text_to_speech(ai_reply)

    except Exception as e:
        print(f"Error: {e}")
        conversation_history.pop()
        continue